### ISSUE TITLE
Linking to a non-existent user's profile results in connection error, not 404

### ISSUE THREAD

**Issue by timmc** [nanote-co/issues#30]
If a user is deleted or if there is a typo in the username, I can't connect to the site at all.

**Comment by kevwu** [comment]
Unfortunately this is because I don't have a wildcard DNS record on HTTPS so I can't catch all domain names. I do have a wildcard record on HTTP but since I have HSTS enabled that's a moot point. I'm not really sure how to resolve this... wildcard certs are prohibitively expensive right now.

**Comment by timmc** [comment]
How do you currently get HTTPS for those subdomains, then?

I'm not super familiar with Cloudflare's offerings, but I see the cert has a whole bunch of SANs (various sites you administer?) including `*.nanote.co`. I'm inferring that they terminate wildcard but reject any subdomain you haven't registered with them.

If you were terminating SSL from the user, I suppose you could do something *very* tricky like registering a letsencrypt cert on the fly as soon as you saw the SNI field come in over TLS. :-P

**Comment by kevwu** [comment]
I'm using Cloudflare's [Universal SSL](https://blog.cloudflare.com/introducing-universal-ssl/). Any traffic proxied through Cloudflare's CDN will automatically be protected. At the moment, I'm using Cloudflare's API to automate creation of CNAME entries for new users. For wildcard entries, Cloudflare only offers DNS but will not proxy traffic, so browsing to any user that doesn't yet exist will result in a bad connection (and falling back to HTTP isn't allowed because of HSTS.)

**Comment by kevwu** [comment]
Seems like this works when you don't use HTTPS:

http://idontexist.nanote.co

vs

https://idontexist.nanote.co

Still not quite sure how to resolve this effectively (and inexpensively).
